---
- name: Deploy Apache
  hosts: labservers
  become: yes
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: latest

    - name: Enable and start httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create index.html file for hosting static content
      copy:
        content: "Hoorraaayyy!! My first playbook ran successfully"
        dest: /var/www/html/index.html
