---
- name: Remove apache Playbook
  hosts: labservers
  become: yes
  tasks:
    - name: Remove the httpd package
      yum:
        name: httpd
        state: absent

    - name: remove firewalld package
      yum:
        name: firewalld
        state: absent
