---
# vars file for roles/db-tier
#
db_pkg:
  - mariadb
  - mariadb-server
  - MySQL-python
  - firewalld
db_srv: mariadb
db:
  user: root
  database: userdb
  password: redhat
  backupfile: userdb.backup
