---
- name: "Install the {{ package }} package"
  yum:
    name: "{{ package }}"
    state: latest

- name: "Start the {{ service }} servvice"
  service:
    name: "{{ service }}"
    state: "{{ svc_state }}"
