---
# tasks file for roles/app-tier
- name: Install Firewalld
  yum:
    name: firewalld
    state: latest

- name: Start firewalld service
  service:
    name: firewalld
    state: started
    enabled: true

- name: Install httpd
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - "{{ httpd_pkg }}"

- name: Start httpd
  service:
    name: "{{ httpd_srv }}"
    enabled: true
    state: started

- name: Copy vhost template file
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
  notify:
    - restart_httpd

- name: Create Document Root
  file:
    path: /var/www/vhost/
    state: directory

- name: Copy index.php file
  copy:
    src: index.php
    dest: /var/www/vhost/index.php
    mode: 0644
    owner: apache
    group: apache

- name: Open httpd port
  firewalld:
    service: http
    state: enabled
    immediate: true
    permanent: true

- name: enable selinux boolean
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  loop:
    - httpd_can_network_connect_db
    - httpd_can_network_connect
